// Package gateway implements the hospital-side enforcement agent.
//
// The security model this package exists to fix:
//
//	Before 0.10.0 the only thing limiting which internal servers a VPN
//	client could reach was the `AllowedIPs` list in the client's own
//	WireGuard config. That is a routing directive, not an access control.
//	A rooted phone, a modified APK, or plain `wg-quick` with the same
//	keypair could set AllowedIPs to 0.0.0.0/0 and reach the entire
//	hospital network. The gateway's own wg0.conf made this worse by
//	installing a blanket `iptables -A FORWARD -i wg0 -j ACCEPT`.
//
//	This package renders the controller's policy into an nftables ruleset
//	with a default-drop forward chain. The client's AllowedIPs list stays
//	(it still decides what the phone bothers to send) but it is no longer
//	load-bearing for security. A client that lies about its AllowedIPs now
//	just gets its packets dropped at the gateway.
//
// Why nftables and not iptables: atomic ruleset replacement. `nft -f` swaps
// the whole table in one transaction, so there is no window during a policy
// reload where the chain is half-built and traffic leaks. Doing the same
// with iptables means either a flush-then-rebuild race or juggling
// iptables-restore semantics.
package gateway

import (
	"fmt"
	"net/netip"
	"sort"
	"strings"
)

// TableName is the nftables table this agent owns. The agent only ever
// touches this table, so an operator's other firewall rules survive a
// policy reload untouched.
const TableName = "aidotvpn"

// Peer is the desired state for one device, as returned by
// GET /node/peers.
type Peer struct {
	DeviceID  string
	PublicKey string
	// Base64 pre-shared key, or "" for none. Must match what the phone
	// mixes into its handshake, or the phone cannot open the gateway's
	// response.
	PSK         string
	IPv4        string
	IPv6        string
	Status      string
	PolicyBound bool
	DestCIDRs   []string
	Rules       []Rule

	// Destinations this peer reaches with its source address rewritten
	// to the gateway's.
	//
	// A subset of DestCIDRs, from policies with source_nat set. It
	// exists for networks where nobody can add a route back to the
	// tunnel pool — a clinic behind a consumer router, a lab on a desk
	// — and the request arriving while the reply is discarded looks
	// exactly like the policy refusing it.
	//
	// The cost is the audit trail: the destination logs the gateway for
	// every device. Off unless an admin turns it on for that policy.
	NATCIDRs []string

	// Destination rewrites: the phone sends to Virtual, the gateway
	// forwards to Real. What lets a handset reach a server it has never
	// been told the address of.
	Rewrites []Rewrite
}

type Rewrite struct {
	Virtual string
	Real    string
}

// Rule is an L4 refinement of DestCIDRs.
type Rule struct {
	Action   string
	Dst      string
	Protocol string
	PortMin  uint16
	PortMax  uint16
}

// RenderOptions controls ruleset generation.
type RenderOptions struct {
	// WGInterface is the WireGuard device name (e.g. "wg0"). Rules match
	// on this as the input interface so the agent never affects traffic
	// arriving on the gateway's other NICs.
	WGInterface string
	// LogDenied emits an nftables log statement before the final drop.
	// Useful during rollout, noisy in steady state — an admin who
	// mis-scopes a policy sees exactly which destination was refused
	// instead of debugging a silent timeout.
	LogDenied bool
	// LogPrefix is prepended to denied-packet log lines.
	LogPrefix string
}

// Render produces a complete `nft -f` script for the given peers.
//
// The output is a full table definition wrapped in a delete+create pair,
// which nft applies atomically. Callers pipe it to `nft -f -`.
func Render(peers []Peer, opt RenderOptions) string {
	iface := opt.WGInterface
	if iface == "" {
		iface = "wg0"
	}
	prefix := opt.LogPrefix
	if prefix == "" {
		prefix = "aidotvpn-deny "
	}

	var b strings.Builder

	b.WriteString("#!/usr/sbin/nft -f\n")
	b.WriteString("# Generated by aidotvpn gateway-agent. DO NOT EDIT BY HAND.\n")
	b.WriteString("# Every policy reload replaces this table atomically.\n\n")

	// `delete table` on a table that doesn't exist is an error in older
	// nft builds, so we create-then-delete. Creating an existing table is
	// a no-op, which makes the pair idempotent on both fresh and warm
	// hosts.
	fmt.Fprintf(&b, "table inet %s {}\n", TableName)
	fmt.Fprintf(&b, "delete table inet %s\n\n", TableName)

	fmt.Fprintf(&b, "table inet %s {\n", TableName)

	// Sort for deterministic output — an unchanged policy must render
	// byte-identical so the agent can skip re-applying it.
	sorted := append([]Peer(nil), peers...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].DeviceID < sorted[j].DeviceID })

	// Locally hosted business services traverse INPUT, not FORWARD.
	// Apply the same policy to decrypted traffic addressed to this gateway.
	b.WriteString("  chain input {\n    type filter hook input priority 0; policy accept;\n")
	fmt.Fprintf(&b, "    iifname != %q accept\n    ct state invalid drop\n", iface)
	for _, p := range sorted {
		writePeerRules(&b, p, iface)
	}
	fmt.Fprintf(&b, "    iifname %q drop\n  }\n", iface)

	fmt.Fprintf(&b, "  chain forward {\n")
	fmt.Fprintf(&b, "    type filter hook forward priority 0; policy drop;\n\n")

	// Return traffic. Without this the reply packets from the permitted
	// server would hit the default drop and every connection would hang
	// after the SYN.
	// Only replies may use conntrack; client packets always re-evaluate policy.
	fmt.Fprintf(&b, "    iifname != %q oifname %q ct state established,related accept\n", iface, iface)
	b.WriteString("    ct state invalid drop\n\n")

	// Traffic that has nothing to do with the tunnel passes through to
	// whatever other rules the host has. We only police wg0.
	fmt.Fprintf(&b, "    iifname != \"%s\" oifname != \"%s\" accept\n\n", iface, iface)

	for _, p := range sorted {
		writePeerRules(&b, p, iface)
	}

	if opt.LogDenied {
		fmt.Fprintf(&b, "    iifname \"%s\" log prefix \"%s\" level info\n", iface, prefix)
	}
	fmt.Fprintf(&b, "    iifname \"%s\" drop\n", iface)
	b.WriteString("  }\n")
	b.WriteString("}\n")

	// NAT table, only when some peer asked for it.
	//
	// A separate table from the filter one above: nft applies each
	// atomically, and mixing a postrouting chain into the filter table
	// would make a policy edit rewrite both. It is also created and
	// deleted unconditionally so a policy that stops using NAT actually
	// loses its rule — leaving a stale masquerade behind would silently
	// keep hiding device addresses after the admin turned it off.
	b.WriteString("\n")
	// create-then-delete, the same idiom as the filter table above:
	// `delete table` on a table that does not exist is an error in older
	// nft builds, and the pair is a no-op on a warm host.
	b.WriteString("table inet aidotvpn_nat {}\n")
	b.WriteString("delete table inet aidotvpn_nat\n")
	b.WriteString("table inet aidotvpn_nat {\n")
	// Rewrites run first, on the way in. A packet for 10.79.0.22 from a
	// device whose policy maps it becomes a packet for 192.168.0.22
	// before the forward chain ever sees it — so the forward rule that
	// permits it is written against the real address, and conntrack
	// un-rewrites the reply on its own.
	b.WriteString("  chain prerouting {\n")
	b.WriteString("    type nat hook prerouting priority dstnat; policy accept;\n")
	for _, p := range peers {
		if p.IPv4 == "" {
			continue
		}
		for _, rw := range p.Rewrites {
			fmt.Fprintf(&b, "    iifname \"wg0\" ip saddr %s ip daddr %s dnat to %s\n",
				p.IPv4, rw.Virtual, rw.Real)
		}
	}
	b.WriteString("  }\n")

	b.WriteString("  chain postrouting {\n")
	b.WriteString("    type nat hook postrouting priority srcnat; policy accept;\n")

	for _, p := range peers {
		for _, cidr := range p.NATCIDRs {
			if p.IPv4 == "" {
				continue
			}
			fmt.Fprintf(&b, "    ip saddr %s ip daddr %s masquerade\n",
				p.IPv4, cidr)
		}
	}

	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}

// writePeerRules emits the accept rules for one peer.
//
// Ordering within a peer matters: explicit drop/reject rules are emitted
// before accepts so that a narrow denial (e.g. "not the admin console on
// this otherwise-permitted subnet") wins over a broader allow. The
// controller already sorts rules that way in GetEffectiveRules; we
// preserve rather than re-derive that order.
func writePeerRules(b *strings.Builder, p Peer, iface string) {
	src := peerSources(p)
	if len(src) == 0 {
		// No tunnel address allocated yet — nothing to match on. The peer
		// still exists in WireGuard so it can complete a handshake, but
		// it forwards nothing.
		fmt.Fprintf(b, "    # %s: no address allocated, no forward rules\n", short(p.DeviceID))
		return
	}

	if !p.PolicyBound {
		// Deny-by-default. An unprovisioned device reaching the gateway
		// is the single most likely real-world mistake (admin registers a
		// phone, forgets to assign a policy), and pre-0.10.0 that mistake
		// granted *full* network access because an empty AllowedIPs list
		// made the client fall back to 0.0.0.0/0.
		fmt.Fprintf(b, "    # %s: NOT policy-bound — denied\n", short(p.DeviceID))
		for _, s := range src {
			fmt.Fprintf(b, "    iifname \"%s\" %s saddr %s drop\n", iface, famOf(s), s)
		}
		b.WriteString("\n")
		return
	}

	fmt.Fprintf(b, "    # %s\n", short(p.DeviceID))

	// L4 rules first — they are the more specific statement of intent.
	covered := map[string]bool{}
	for _, r := range p.Rules {
		dst, err := netip.ParsePrefix(r.Dst)
		if err != nil {
			continue
		}
		verdict := nftVerdict(r.Action)
		if verdict == "" {
			continue
		}
		if verdict == "accept" {
			covered[dst.String()] = true
		}
		for _, s := range src {
			if famOf(s) != famOf(dst.String()) {
				continue
			}
			fmt.Fprintf(b, "    iifname \"%s\" %s saddr %s %s daddr %s%s %s\n",
				iface, famOf(s), s, famOf(dst.String()), dst.String(),
				l4Match(r), verdict)
		}
	}

	// A broad bare CIDR must not bypass a narrower port-only allow.
	coveredPrefixes := make([]string, 0, len(covered))
	for cidr := range covered {
		coveredPrefixes = append(coveredPrefixes, cidr)
	}
	sort.Strings(coveredPrefixes)
	for _, cidr := range coveredPrefixes {
		for _, source := range src {
			if famOf(source) == famOf(cidr) {
				fmt.Fprintf(b, "    iifname %q %s saddr %s %s daddr %s drop\n", iface, famOf(source), source, famOf(cidr), cidr)
			}
		}
	}

	// Bare CIDR accepts for destinations no L4 rule already covers. A
	// policy with CIDRs but no rules — which is what the console's
	// "허용 CIDR" screen alone produces — lands entirely here.
	for _, c := range p.DestCIDRs {
		dst, err := netip.ParsePrefix(c)
		if err != nil {
			continue
		}
		if covered[dst.String()] {
			continue
		}
		for _, s := range src {
			if famOf(s) != famOf(dst.String()) {
				continue
			}
			fmt.Fprintf(b, "    iifname \"%s\" %s saddr %s %s daddr %s accept\n",
				iface, famOf(s), s, famOf(dst.String()), dst.String())
		}
	}
	b.WriteString("\n")
}

// peerSources returns the peer's tunnel addresses as /32 or /128 prefixes.
func peerSources(p Peer) []string {
	var out []string
	if p.IPv4 != "" {
		if a, err := netip.ParseAddr(p.IPv4); err == nil && a.Is4() {
			out = append(out, a.String()+"/32")
		}
	}
	if p.IPv6 != "" {
		if a, err := netip.ParseAddr(p.IPv6); err == nil && a.Is6() {
			out = append(out, a.String()+"/128")
		}
	}
	return out
}

// famOf returns the nftables family keyword for an address or prefix.
func famOf(s string) string {
	base := s
	if i := strings.IndexByte(s, '/'); i >= 0 {
		base = s[:i]
	}
	a, err := netip.ParseAddr(base)
	if err != nil {
		return "ip"
	}
	if a.Is4() {
		return "ip"
	}
	return "ip6"
}

// l4Match renders the protocol/port portion of a rule, with a leading
// space, or "" for protocol-any rules.
func l4Match(r Rule) string {
	switch r.Protocol {
	case "tcp", "udp":
		if r.PortMin == 0 && r.PortMax == 0 {
			return " meta l4proto " + r.Protocol
		}
		if r.PortMin == r.PortMax {
			return fmt.Sprintf(" %s dport %d", r.Protocol, r.PortMin)
		}
		return fmt.Sprintf(" %s dport %d-%d", r.Protocol, r.PortMin, r.PortMax)
	case "icmp":
		return " ip protocol icmp"
	case "icmpv6":
		// Protocol 58 avoids an /etc/protocols dependency in minimal images.
		// Keep l4proto so IPv6 extension headers are handled correctly.
		return " meta l4proto 58"
	default:
		return ""
	}
}

// nftVerdict maps a policy action to an nftables verdict. Unknown actions
// return "" so the caller skips the rule rather than guessing — silently
// downgrading an unrecognised action to `accept` would be the worst
// possible failure mode here.
func nftVerdict(action string) string {
	switch action {
	case "accept":
		return "accept"
	case "reject":
		return "reject"
	case "drop":
		return "drop"
	default:
		return ""
	}
}

func short(id string) string {
	if len(id) > 12 {
		return id[:12]
	}
	return id
}
