'use strict';
const $ = id => document.getElementById(id);
const english = { subtitle:'Open your console and manage the server connection.',connection:'Console connection',connect:'Connect to an existing console',connectHelp:'Open a console hosted by a Windows service or remote server.',bundled:'Run a console on this PC',bundledHelp:'Use the bundled executables. No separate Node.js installation is required.',consoleURL:'Console URL',httpsHelp:'Remote URLs require HTTPS with a certificate trusted by Windows.',controllerURL:'Controller URL',port:'Local console port',localHelp:'The console accepts connections on 127.0.0.1 only. The VPN gateway requires a separate Linux server.',startController:'Also run the bundled controller',envFile:'Controller configuration file',browse:'Browse',dbHelp:'Select controller.env with your existing MariaDB settings and device CA. Starting the controller applies DB migrations.',template:'Open configuration example folder',autoStart:'Start in the tray when I sign in to Windows',closeHelp:'Closing a window keeps the app running. Quit from the tray to stop this app and the servers it started.',logs:'Open logs',save:'Check connection and open console' };
const korean = Object.fromEntries([...document.querySelectorAll('[data-i18n]')].map(el => [el.dataset.i18n, el.textContent]));
let locale='ko', connected=false, busy=false;
function translate() { document.documentElement.lang=locale; for(const el of document.querySelectorAll('[data-i18n]')) el.textContent=(locale==='en'?english:korean)[el.dataset.i18n]; updateStatus(); }
function updateStatus() { $('status').classList.toggle('ready',connected); $('status').textContent=busy?(locale==='ko'?'서버 연결을 확인하고 있습니다…':'Checking the server connection…'):connected?(locale==='ko'?'콘솔에 연결되어 있습니다.':'Connected to the console.'):(locale==='ko'?'연결 방식을 선택하고 콘솔 주소를 확인하세요.':'Choose a connection mode and check the console address.'); }
function fields() { const local=document.querySelector('[name=mode]:checked').value==='bundled'; $('connectFields').hidden=local; $('bundledFields').hidden=!local; $('controllerFields').hidden=!$('startController').checked; }
function error(message) { $('error').textContent=message||''; $('error').hidden=!message; }
async function call(name,...args) { const result=await window.aidotDesktop[name](...args); if(!result.ok)throw Error(result.error); return result.value; }
function formValue() { return {mode:document.querySelector('[name=mode]:checked').value,consoleURL:$('consoleURL').value,controllerURL:$('controllerURL').value,localPort:Number($('localPort').value),controllerEnv:$('controllerEnv').value,startController:$('startController').checked,autoStart:$('autoStart').checked,locale}; }
document.querySelectorAll('[name=mode]').forEach(el=>el.addEventListener('change',fields));
$('startController').addEventListener('change',fields);
$('locale').addEventListener('change',()=>{locale=$('locale').value;translate();});
for(const [button,method] of [['logs','openLogs'],['template','createTemplate']]) $(button).addEventListener('click',()=>call(method).catch(e=>error(e.message)));
$('chooseEnv').addEventListener('click',async()=>{try{const file=await call('chooseEnv');if(file)$('controllerEnv').value=file;}catch(e){error(e.message);}});
$('settings').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;busy=true;error('');updateStatus();$('save').disabled=true;try{await call('apply',formValue());connected=true;}catch(e){error(e.message);}finally{busy=false;$('save').disabled=false;updateStatus();}});
(async()=>{try{const state=await call('state'),c=state.config;locale=c.locale;connected=state.connected;$('locale').value=locale;document.querySelector('[name=mode][value='+c.mode+']').checked=true;for(const k of ['consoleURL','controllerURL','localPort','controllerEnv'])$(k).value=c[k];for(const k of ['startController','autoStart'])$(k).checked=c[k];$('version').textContent='AidotVPN Desktop '+state.version;fields();translate();}catch(e){error(e.message);}})();
